#!/bin/bash -l
# Standard output and error:
#SBATCH -o ./tjob.out.%j
#SBATCH -e ./tjob.err.%j
# Initial working directory:
#SBATCH -D ./
# Job Name:
#SBATCH -J name
#
# Queue (Partition):
#SBATCH --partition=s.phys  
#SBATCH --mem=50000  
#
# Number of nodes and MPI tasks per node:
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1  
#SBATCH --cpus-per-task=9
#
#SBATCH --mail-type=none
#SBATCH --mail-user=<userid>@rzg.mpg.de
#
# Wall clock limit:
#SBATCH --time=04:00:00

#module load purge
module load intel/19.1.3
module load impi/2019.9
module load gromacs/2019.6

sys=$1

srun gmx mdrun -v -deffnm $sys"_npt"
