#!/bin/bash -l
# Standard output and error:
#SBATCH -o ./tjob.out.%j
#SBATCH -e ./tjob.err.%j
# Initial working directory:
#SBATCH -D ./
# Job Name:
#SBATCH -J name
#
# Queue:
#SBATCH --partition=s.phys       # NEEDED; otherwise the job blocks a whole node
#SBATCH --mem=70000             # Memory is necessary if using only part of a node
#
# Number of nodes and MPI tasks per node:
# SBATCH --nodes=1
#SBATCH --ntasks-per-node=20
#
#SBATCH --mail-type=none
#SBATCH --mail-user=<userid>@rzg.mpg.de
#
# Wall clock limit:
#SBATCH --time=02:00:00

#module load purge
module load intel/19.1.3
module load impi/2019.9
module load gromacs/2019.6

script=$1
s=$2 # first fragment
e=$3 # last fragment
sys=$4
for i in $(seq $s $e) ; do
 cd $i
 bash $script $sys
 cd .. ; 
done
